# Generated by Django 6.0.5 on 2026-05-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=200)),
                ('book_des', models.CharField(max_length=100)),
                ('book_type', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_price', models.IntegerField()),
                ('book_quantity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
